version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command: |
            ./gradlew clean
            echo 'This is the delivery pipeline'