version: 2.1


orbs:
  android: circleci/android@0.2.0
jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          name: "create debug build"
          command: ${publish_command}


#version: 2.1
#orbs:
#  android: circleci/android@0.2.0
#jobs:
#  build:
#    executor: android/android
##    docker:
##      - image: alpine:3.15
#    steps:
#      - checkout
#          - run:
#            name: "build"
#            command: ./gradlew assembleDebug
#      - run:
#          name: The First Step
#          command: |
#            ./gradlew clean
#            echo 'This is the delivery pipeline'

#            ./gradlew clean artifactoryPublish