version: 2.1
orbs:
  android: circleci/android@0.2.0
jobs:
  build:
    executor: android/android
#    docker:
#      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command: |
            ./gradlew clean
            echo 'This is the delivery pipeline'

#            ./gradlew clean artifactoryPublish