version: 2.1
orbs:
  gradle: circleci/gradle@3.0.0
jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command: |
            gradlew clean
            echo 'This is the delivery pipeline'