version: 2.1


orbs:
  android: circleci/android@0.2.0
  aws-cli: circleci/aws-cli@3.1
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run: echo "Run your code here"
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          name: "publish aar to jFrog"
          command: ${publish_command}

